// var response = `{
//     "articles": [{
//             "contentType": "TAX_CONTENT_TYPE_ARTICLE",
//             "imageCredit": null,
//             "imageDescriptionText": "",
//             "relatedContacts": [],
//             "relatedContent": [],
//             "title": "Final regulations released for partnerships that pay or accrue foreign income taxes",
//             "teaserText": "Regulations address allocation of creditable foreign income taxes",
//             "publishDateTime": 1563917940000,
//             "authorName": "Ari Berk",
//             "availableLanguages": [{
//                 "localisationIdentifier": "en",
//                 "enabled": true,
//                 "language": "en",
//                 "country": "",
//                 "description": "English",
//                 "uuid": "37",
//                 "name": "English",
//                 "path": "/locales/en",
//                 "rightToLeft": false,
//                 "completeResponse": true,
//                 "scriptDirection": "ltr"
//             }],
//             "relatedCountry": {
//                 "pngimagePath": null,
//                 "svgimagePath": null,
//                 "displayName": "United States",
//                 "displayNameShort": "USA",
//                 "providerName": "",
//                 "providerTerms": "",
//                 "uuid": "29",
//                 "name": "United States",
//                 "path": "United-States",
//                 "completeResponse": false
//             },
//             "relatedCountries": [{
//                 "pngimagePath": null,
//                 "svgimagePath": null,
//                 "displayName": "United States",
//                 "displayNameShort": "USA",
//                 "providerName": "",
//                 "providerTerms": "",
//                 "uuid": "29",
//                 "name": "United States",
//                 "path": "United-States",
//                 "completeResponse": false
//             }],
//             "isRead": false,
//             "saved": false,
//             "savedDate": 0,
//             "articleHtml": "",
//             "relatedTags": [{
//                     "countries": [],
//                     "displayName": "Taxable income",
//                     "uuid": "32",
//                     "name": "Taxable income",
//                     "path": null,
//                     "completeResponse": false,
//                     "subscribed": false,
//                     "parentTagName": "Core Tax Topics",
//                     "parentTagId": 32
//                 },
//                 {
//                     "countries": [],
//                     "displayName": "Multinational enterprises",
//                     "uuid": "45",
//                     "name": "Multinational enterprises",
//                     "path": null,
//                     "completeResponse": false,
//                     "subscribed": false,
//                     "parentTagName": "Businesses",
//                     "parentTagId": 45
//                 },
//                 {
//                     "countries": [],
//                     "displayName": "Partnerships",
//                     "uuid": "46",
//                     "name": "Partnerships",
//                     "path": null,
//                     "completeResponse": false,
//                     "subscribed": false,
//                     "parentTagName": "Businesses",
//                     "parentTagId": 46
//                 },
//                 {
//                     "countries": [],
//                     "displayName": "International tax",
//                     "uuid": "68",
//                     "name": "International tax",
//                     "path": null,
//                     "completeResponse": false,
//                     "subscribed": false,
//                     "parentTagName": "Cross Border Taxes",
//                     "parentTagId": 68
//                 },
//                 {
//                     "countries": [],
//                     "displayName": "Regulations",
//                     "uuid": "188",
//                     "name": "Regulations",
//                     "path": null,
//                     "completeResponse": false,
//                     "subscribed": false,
//                     "parentTagName": "Tax Policy & Law",
//                     "parentTagId": 188
//                 },
//                 {
//                     "countries": [],
//                     "displayName": "IRS",
//                     "uuid": "236",
//                     "name": "IRS",
//                     "path": null,
//                     "completeResponse": false,
//                     "subscribed": false,
//                     "parentTagName": "Tax Administration",
//                     "parentTagId": 236
//                 },
//                 {
//                     "countries": [],
//                     "displayName": "Pass-throughs",
//                     "uuid": "424",
//                     "name": "Pass-throughs",
//                     "path": null,
//                     "completeResponse": false,
//                     "subscribed": false,
//                     "parentTagName": "Businesses",
//                     "parentTagId": 424
//                 }
//             ],
//             "relatedSubscriptions": [],
//             "groupName": null,
//             "groupPosition": null,
//             "resourcePosition": null,
//             "sharingWebURL": "https://www.taxathand.com/article/11979/United-States/2019/Final-regulations-released-for-partnerships-that-pay-or-accrue-foreign-income-taxes",
//             "imagePath": "https://www.taxathand.com/api/tax/v1/article/45390/image",
//             "subscribed": false,
//             "uuid": "11979",
//             "name": "Final regulations released for partnerships that pay or accrue foreign income taxes",
//             "path": "11979/United-States/2019/Final-regulations-released-for-partnerships-that-pay-or-accrue-foreign-income-taxes",
//             "completeResponse": false,
//             "titleInEnglishDefault": "Final regulations released for partnerships that pay or accrue foreign income taxes",
//             "province": null,
//             "languageId": "37",
//             "containsYoutubeLink": false
//         },
//         {
//             "contentType": "TAX_CONTENT_TYPE_ARTICLE",
//             "imageCredit": null,
//             "imageDescriptionText": "",
//             "relatedContacts": [],
//             "relatedContent": [],
//             "title": "G7 leaders endorse direction of OECD consensus project on digital taxation",
//             "teaserText": "Proposed work plan envisions a two-pillar approach and group hopes to reach a consensus by the end of 2020",
//             "publishDateTime": 1563598320000,
//             "authorName": "Storme Sixeas",
//             "availableLanguages": [{
//                 "localisationIdentifier": "en",
//                 "enabled": true,
//                 "language": "en",
//                 "country": "",
//                 "description": "English",
//                 "uuid": "37",
//                 "name": "English",
//                 "path": "/locales/en",
//                 "rightToLeft": false,
//                 "completeResponse": true,
//                 "scriptDirection": "ltr"
//             }],
//             "relatedCountry": {
//                 "pngimagePath": null,
//                 "svgimagePath": null,
//                 "displayName": "United States",
//                 "displayNameShort": "USA",
//                 "providerName": "",
//                 "providerTerms": "",
//                 "uuid": "29",
//                 "name": "United States",
//                 "path": "United-States",
//                 "completeResponse": false
//             },
//             "relatedCountries": [{
//                 "pngimagePath": null,
//                 "svgimagePath": null,
//                 "displayName": "United States",
//                 "displayNameShort": "USA",
//                 "providerName": "",
//                 "providerTerms": "",
//                 "uuid": "29",
//                 "name": "United States",
//                 "path": "United-States",
//                 "completeResponse": false
//             }],
//             "isRead": false,
//             "saved": false,
//             "savedDate": 0,
//             "articleHtml": "",
//             "relatedTags": [{
//                     "countries": [],
//                     "displayName": "Corporate income tax",
//                     "uuid": "15",
//                     "name": "Corporate income tax",
//                     "path": null,
//                     "completeResponse": false,
//                     "subscribed": false,
//                     "parentTagName": "Core Tax Topics",
//                     "parentTagId": 15
//                 },
//                 {
//                     "countries": [],
//                     "displayName": "Companies",
//                     "uuid": "35",
//                     "name": "Companies",
//                     "path": null,
//                     "completeResponse": false,
//                     "subscribed": false,
//                     "parentTagName": "Businesses",
//                     "parentTagId": 35
//                 },
//                 {
//                     "countries": [],
//                     "displayName": "Corporations",
//                     "uuid": "36",
//                     "name": "Corporations",
//                     "path": null,
//                     "completeResponse": false,
//                     "subscribed": false,
//                     "parentTagName": "Businesses",
//                     "parentTagId": 36
//                 },
//                 {
//                     "countries": [],
//                     "displayName": "Multinational enterprises",
//                     "uuid": "45",
//                     "name": "Multinational enterprises",
//                     "path": null,
//                     "completeResponse": false,
//                     "subscribed": false,
//                     "parentTagName": "Businesses",
//                     "parentTagId": 45
//                 },
//                 {
//                     "countries": [],
//                     "displayName": "International tax",
//                     "uuid": "68",
//                     "name": "International tax",
//                     "path": null,
//                     "completeResponse": false,
//                     "subscribed": false,
//                     "parentTagName": "Cross Border Taxes",
//                     "parentTagId": 68
//                 },
//                 {
//                     "countries": [],
//                     "displayName": "Legislation",
//                     "uuid": "186",
//                     "name": "Legislation",
//                     "path": null,
//                     "completeResponse": false,
//                     "subscribed": false,
//                     "parentTagName": "Tax Policy & Law",
//                     "parentTagId": 186
//                 },
//                 {
//                     "countries": [],
//                     "displayName": "OECD",
//                     "uuid": "187",
//                     "name": "OECD",
//                     "path": null,
//                     "completeResponse": false,
//                     "subscribed": false,
//                     "parentTagName": "Tax Policy & Law",
//                     "parentTagId": 187
//                 },
//                 {
//                     "countries": [],
//                     "displayName": "Tax policy & reform",
//                     "uuid": "192",
//                     "name": "Tax policy & reform",
//                     "path": null,
//                     "completeResponse": false,
//                     "subscribed": false,
//                     "parentTagName": "Tax Policy & Law",
//                     "parentTagId": 192
//                 }
//             ],
//             "relatedSubscriptions": [],
//             "groupName": null,
//             "groupPosition": null,
//             "resourcePosition": null,
//             "sharingWebURL": "https://www.taxathand.com/article/11965/United-States/2019/G7-leaders-endorse-direction-of-OECD-consensus-project-on-digital-taxation",
//             "imagePath": "https://www.taxathand.com/api/tax/v1/article/45133/image",
//             "subscribed": false,
//             "uuid": "11965",
//             "name": "G7 leaders endorse direction of OECD consensus project on digital taxation",
//             "path": "11965/United-States/2019/G7-leaders-endorse-direction-of-OECD-consensus-project-on-digital-taxation",
//             "completeResponse": false,
//             "titleInEnglishDefault": "G7 leaders endorse direction of OECD consensus project on digital taxation",
//             "province": null,
//             "languageId": "37",
//             "containsYoutubeLink": false
//         },
//         {
//             "contentType": "TAX_CONTENT_TYPE_ARTICLE",
//             "imageCredit": null,
//             "imageDescriptionText": "",
//             "relatedContacts": [],
//             "relatedContent": [],
//             "title": "House, Senate Democrats seek to invalidate final regs limiting SALT cap workarounds",
//             "teaserText": "Resolutions unlikely to garner two-thirds supermajority support needed to override presidential veto",
//             "publishDateTime": 1563594120000,
//             "authorName": "Michael DeHoff",
//             "availableLanguages": [{
//                 "localisationIdentifier": "en",
//                 "enabled": true,
//                 "language": "en",
//                 "country": "",
//                 "description": "English",
//                 "uuid": "37",
//                 "name": "English",
//                 "path": "/locales/en",
//                 "rightToLeft": false,
//                 "completeResponse": true,
//                 "scriptDirection": "ltr"
//             }],
//             "relatedCountry": {
//                 "pngimagePath": null,
//                 "svgimagePath": null,
//                 "displayName": "United States",
//                 "displayNameShort": "USA",
//                 "providerName": "",
//                 "providerTerms": "",
//                 "uuid": "29",
//                 "name": "United States",
//                 "path": "United-States",
//                 "completeResponse": false
//             },
//             "relatedCountries": [{
//                 "pngimagePath": null,
//                 "svgimagePath": null,
//                 "displayName": "United States",
//                 "displayNameShort": "USA",
//                 "providerName": "",
//                 "providerTerms": "",
//                 "uuid": "29",
//                 "name": "United States",
//                 "path": "United-States",
//                 "completeResponse": false
//             }],
//             "isRead": false,
//             "saved": false,
//             "savedDate": 0,
//             "articleHtml": "",
//             "relatedTags": [{
//                     "countries": [],
//                     "displayName": "Deductions",
//                     "uuid": "16",
//                     "name": "Deductions",
//                     "path": null,
//                     "completeResponse": false,
//                     "subscribed": false,
//                     "parentTagName": "Core Tax Topics",
//                     "parentTagId": 16
//                 },
//                 {
//                     "countries": [],
//                     "displayName": "Individual income tax",
//                     "uuid": "20",
//                     "name": "Individual income tax",
//                     "path": null,
//                     "completeResponse": false,
//                     "subscribed": false,
//                     "parentTagName": "Core Tax Topics",
//                     "parentTagId": 20
//                 },
//                 {
//                     "countries": [],
//                     "displayName": "Tax credit",
//                     "uuid": "28",
//                     "name": "Tax credit",
//                     "path": null,
//                     "completeResponse": false,
//                     "subscribed": false,
//                     "parentTagName": "Core Tax Topics",
//                     "parentTagId": 28
//                 },
//                 {
//                     "countries": [],
//                     "displayName": "Individuals",
//                     "uuid": "157",
//                     "name": "Individuals",
//                     "path": null,
//                     "completeResponse": false,
//                     "subscribed": false,
//                     "parentTagName": "Individuals",
//                     "parentTagId": 157
//                 },
//                 {
//                     "countries": [],
//                     "displayName": "Legislation",
//                     "uuid": "186",
//                     "name": "Legislation",
//                     "path": null,
//                     "completeResponse": false,
//                     "subscribed": false,
//                     "parentTagName": "Tax Policy & Law",
//                     "parentTagId": 186
//                 },
//                 {
//                     "countries": [],
//                     "displayName": "Regulations",
//                     "uuid": "188",
//                     "name": "Regulations",
//                     "path": null,
//                     "completeResponse": false,
//                     "subscribed": false,
//                     "parentTagName": "Tax Policy & Law",
//                     "parentTagId": 188
//                 },
//                 {
//                     "countries": [],
//                     "displayName": "Tax policy & reform",
//                     "uuid": "192",
//                     "name": "Tax policy & reform",
//                     "path": null,
//                     "completeResponse": false,
//                     "subscribed": false,
//                     "parentTagName": "Tax Policy & Law",
//                     "parentTagId": 192
//                 },
//                 {
//                     "countries": [],
//                     "displayName": "Charities & NPOs",
//                     "uuid": "250",
//                     "name": "Charities & NPOs",
//                     "path": null,
//                     "completeResponse": false,
//                     "subscribed": false,
//                     "parentTagName": "Not-For-Profits",
//                     "parentTagId": 250
//                 },
//                 {
//                     "countries": [],
//                     "displayName": "Local taxes",
//                     "uuid": "264",
//                     "name": "Local taxes",
//                     "path": null,
//                     "completeResponse": false,
//                     "subscribed": false,
//                     "parentTagName": "Regional Taxes",
//                     "parentTagId": 264
//                 },
//                 {
//                     "countries": [],
//                     "displayName": "State taxes",
//                     "uuid": "469",
//                     "name": "State taxes",
//                     "path": null,
//                     "completeResponse": false,
//                     "subscribed": false,
//                     "parentTagName": "Regional Taxes",
//                     "parentTagId": 469
//                 }
//             ],
//             "relatedSubscriptions": [],
//             "groupName": null,
//             "groupPosition": null,
//             "resourcePosition": null,
//             "sharingWebURL": "https://www.taxathand.com/article/11963/United-States/2019/House-Senate-Democrats-seek-to-invalidate-final-regs-limiting-SALT-cap-workarounds",
//             "imagePath": "https://www.taxathand.com/api/tax/v1/article/45110/image",
//             "subscribed": false,
//             "uuid": "11963",
//             "name": "House, Senate Democrats seek to invalidate final regs limiting SALT cap workarounds",
//             "path": "11963/United-States/2019/House-Senate-Democrats-seek-to-invalidate-final-regs-limiting-SALT-cap-workarounds",
//             "completeResponse": false,
//             "titleInEnglishDefault": "House, Senate Democrats seek to invalidate final regs limiting SALT cap workarounds",
//             "province": null,
//             "languageId": "37",
//             "containsYoutubeLink": false
//         },
//         {
//             "contentType": "TAX_CONTENT_TYPE_ARTICLE",
//             "imageCredit": null,
//             "imageDescriptionText": "",
//             "relatedContacts": [],
//             "relatedContent": [],
//             "title": "House votes to repeal “Cadillac” tax on high-cost health plans",
//             "teaserText": "Senate action remains unclear but House repeal could be gateway to an extenders deal",
//             "publishDateTime": 1563591480000,
//             "authorName": "Alex Brosseau",
//             "availableLanguages": [{
//                 "localisationIdentifier": "en",
//                 "enabled": true,
//                 "language": "en",
//                 "country": "",
//                 "description": "English",
//                 "uuid": "37",
//                 "name": "English",
//                 "path": "/locales/en",
//                 "rightToLeft": false,
//                 "completeResponse": true,
//                 "scriptDirection": "ltr"
//             }],
//             "relatedCountry": {
//                 "pngimagePath": null,
//                 "svgimagePath": null,
//                 "displayName": "United States",
//                 "displayNameShort": "USA",
//                 "providerName": "",
//                 "providerTerms": "",
//                 "uuid": "29",
//                 "name": "United States",
//                 "path": "United-States",
//                 "completeResponse": false
//             },
//             "relatedCountries": [{
//                 "pngimagePath": null,
//                 "svgimagePath": null,
//                 "displayName": "United States",
//                 "displayNameShort": "USA",
//                 "providerName": "",
//                 "providerTerms": "",
//                 "uuid": "29",
//                 "name": "United States",
//                 "path": "United-States",
//                 "completeResponse": false
//             }],
//             "isRead": false,
//             "saved": false,
//             "savedDate": 0,
//             "articleHtml": "",
//             "relatedTags": [{
//                     "countries": [],
//                     "displayName": "Deductions",
//                     "uuid": "16",
//                     "name": "Deductions",
//                     "path": null,
//                     "completeResponse": false,
//                     "subscribed": false,
//                     "parentTagName": "Core Tax Topics",
//                     "parentTagId": 16
//                 },
//                 {
//                     "countries": [],
//                     "displayName": "Tax credit",
//                     "uuid": "28",
//                     "name": "Tax credit",
//                     "path": null,
//                     "completeResponse": false,
//                     "subscribed": false,
//                     "parentTagName": "Core Tax Topics",
//                     "parentTagId": 28
//                 },
//                 {
//                     "countries": [],
//                     "displayName": "Companies",
//                     "uuid": "35",
//                     "name": "Companies",
//                     "path": null,
//                     "completeResponse": false,
//                     "subscribed": false,
//                     "parentTagName": "Businesses",
//                     "parentTagId": 35
//                 },
//                 {
//                     "countries": [],
//                     "displayName": "Employee benefits",
//                     "uuid": "81",
//                     "name": "Employee benefits",
//                     "path": null,
//                     "completeResponse": false,
//                     "subscribed": false,
//                     "parentTagName": "Employment Taxes",
//                     "parentTagId": 81
//                 },
//                 {
//                     "countries": [],
//                     "displayName": "Customs & Excise",
//                     "uuid": "123",
//                     "name": "Customs & Excise",
//                     "path": null,
//                     "completeResponse": false,
//                     "subscribed": false,
//                     "parentTagName": "Indirect Taxes",
//                     "parentTagId": 123
//                 },
//                 {
//                     "countries": [],
//                     "displayName": "Individuals",
//                     "uuid": "157",
//                     "name": "Individuals",
//                     "path": null,
//                     "completeResponse": false,
//                     "subscribed": false,
//                     "parentTagName": "Individuals",
//                     "parentTagId": 157
//                 },
//                 {
//                     "countries": [],
//                     "displayName": "Legislation",
//                     "uuid": "186",
//                     "name": "Legislation",
//                     "path": null,
//                     "completeResponse": false,
//                     "subscribed": false,
//                     "parentTagName": "Tax Policy & Law",
//                     "parentTagId": 186
//                 },
//                 {
//                     "countries": [],
//                     "displayName": "Tax policy & reform",
//                     "uuid": "192",
//                     "name": "Tax policy & reform",
//                     "path": null,
//                     "completeResponse": false,
//                     "subscribed": false,
//                     "parentTagName": "Tax Policy & Law",
//                     "parentTagId": 192
//                 },
//                 {
//                     "countries": [],
//                     "displayName": "Tax incentives",
//                     "uuid": "202",
//                     "name": "Tax incentives",
//                     "path": null,
//                     "completeResponse": false,
//                     "subscribed": false,
//                     "parentTagName": "R&D & Incentives",
//                     "parentTagId": 202
//                 },
//                 {
//                     "countries": [],
//                     "displayName": "Employees",
//                     "uuid": "366",
//                     "name": "Employees",
//                     "path": null,
//                     "completeResponse": false,
//                     "subscribed": false,
//                     "parentTagName": "Employment Taxes",
//                     "parentTagId": 366
//                 }
//             ],
//             "relatedSubscriptions": [],
//             "groupName": null,
//             "groupPosition": null,
//             "resourcePosition": null,
//             "sharingWebURL": "https://www.taxathand.com/article/11962/United-States/2019/House-votes-to-repeal-Cadillac-tax-on-high-cost-health-plans",
//             "imagePath": "https://www.taxathand.com/api/tax/v1/article/44693/image",
//             "subscribed": false,
//             "uuid": "11962",
//             "name": "House votes to repeal “Cadillac” tax on high-cost health plans",
//             "path": "11962/United-States/2019/House-votes-to-repeal-Cadillac-tax-on-high-cost-health-plans",
//             "completeResponse": false,
//             "titleInEnglishDefault": "House votes to repeal “Cadillac” tax on high-cost health plans",
//             "province": null,
//             "languageId": "37",
//             "containsYoutubeLink": false
//         },
//         {
//             "contentType": "TAX_CONTENT_TYPE_ARTICLE",
//             "imageCredit": null,
//             "imageDescriptionText": "",
//             "relatedContacts": [],
//             "relatedContent": [],
//             "title": "2013 protocol to Japan-US tax treaty approved by US Senate",
//             "teaserText": "Broad exemption for interest withholding tax",
//             "publishDateTime": 1563580920000,
//             "authorName": "",
//             "availableLanguages": [{
//                     "localisationIdentifier": "en",
//                     "enabled": true,
//                     "language": "en",
//                     "country": "",
//                     "description": "English",
//                     "uuid": "37",
//                     "name": "English",
//                     "path": "/locales/en",
//                     "rightToLeft": false,
//                     "completeResponse": true,
//                     "scriptDirection": "ltr"
//                 },
//                 {
//                     "localisationIdentifier": "ja",
//                     "enabled": true,
//                     "language": "ja",
//                     "country": "",
//                     "description": "日本語",
//                     "uuid": "96",
//                     "name": "日本語",
//                     "path": "/locales/ja",
//                     "rightToLeft": false,
//                     "completeResponse": true,
//                     "scriptDirection": "ltr"
//                 }
//             ],
//             "relatedCountry": {
//                 "pngimagePath": null,
//                 "svgimagePath": null,
//                 "displayName": "Japan",
//                 "displayNameShort": "Japan",
//                 "providerName": "",
//                 "providerTerms": "",
//                 "uuid": "14",
//                 "name": "Japan",
//                 "path": "Japan",
//                 "completeResponse": false
//             },
//             "relatedCountries": [{
//                     "pngimagePath": null,
//                     "svgimagePath": null,
//                     "displayName": "Japan",
//                     "displayNameShort": "Japan",
//                     "providerName": "",
//                     "providerTerms": "",
//                     "uuid": "14",
//                     "name": "Japan",
//                     "path": "Japan",
//                     "completeResponse": false
//                 },
//                 {
//                     "pngimagePath": null,
//                     "svgimagePath": null,
//                     "displayName": "United States",
//                     "displayNameShort": "USA",
//                     "providerName": "",
//                     "providerTerms": "",
//                     "uuid": "29",
//                     "name": "United States",
//                     "path": "United-States",
//                     "completeResponse": false
//                 }
//             ],
//             "isRead": false,
//             "saved": false,
//             "savedDate": 0,
//             "articleHtml": "",
//             "relatedTags": [{
//                     "countries": [],
//                     "displayName": "Capital gains",
//                     "uuid": "14",
//                     "name": "Capital gains",
//                     "path": null,
//                     "completeResponse": false,
//                     "subscribed": false,
//                     "parentTagName": "Core Tax Topics",
//                     "parentTagId": 14
//                 },
//                 {
//                     "countries": [],
//                     "displayName": "Treaties",
//                     "uuid": "78",
//                     "name": "Treaties",
//                     "path": null,
//                     "completeResponse": false,
//                     "subscribed": false,
//                     "parentTagName": "Cross Border Taxes",
//                     "parentTagId": 78
//                 },
//                 {
//                     "countries": [],
//                     "displayName": "Real estate",
//                     "uuid": "140",
//                     "name": "Real estate",
//                     "path": null,
//                     "completeResponse": false,
//                     "subscribed": false,
//                     "parentTagName": "Indirect Taxes",
//                     "parentTagId": 140
//                 },
//                 {
//                     "countries": [],
//                     "displayName": "Mutual agreement procedure",
//                     "uuid": "211",
//                     "name": "Mutual agreement procedure",
//                     "path": null,
//                     "completeResponse": false,
//                     "subscribed": false,
//                     "parentTagName": "Treaties",
//                     "parentTagId": 211
//                 },
//                 {
//                     "countries": [],
//                     "displayName": "Dividend withholding tax",
//                     "uuid": "348",
//                     "name": "Dividend withholding tax",
//                     "path": null,
//                     "completeResponse": false,
//                     "subscribed": false,
//                     "parentTagName": "Withholding Taxes",
//                     "parentTagId": 348
//                 },
//                 {
//                     "countries": [],
//                     "displayName": "Interest withholding tax",
//                     "uuid": "349",
//                     "name": "Interest withholding tax",
//                     "path": null,
//                     "completeResponse": false,
//                     "subscribed": false,
//                     "parentTagName": "Withholding Taxes",
//                     "parentTagId": 349
//                 },
//                 {
//                     "countries": [],
//                     "displayName": "Arbitration",
//                     "uuid": "429",
//                     "name": "Arbitration",
//                     "path": null,
//                     "completeResponse": false,
//                     "subscribed": false,
//                     "parentTagName": "Tax Controversy",
//                     "parentTagId": 429
//                 }
//             ],
//             "relatedSubscriptions": [],
//             "groupName": null,
//             "groupPosition": null,
//             "resourcePosition": null,
//             "sharingWebURL": "https://www.taxathand.com/article/11960/Japan/2019/2013-protocol-to-Japan-US-tax-treaty-approved-by-US-Senate",
//             "imagePath": "https://www.taxathand.com/api/tax/v1/article/44698/image",
//             "subscribed": false,
//             "uuid": "11960",
//             "name": "2013 protocol to Japan-US tax treaty approved by US Senate",
//             "path": "11960/Japan/2019/2013-protocol-to-Japan-US-tax-treaty-approved-by-US-Senate",
//             "completeResponse": false,
//             "titleInEnglishDefault": "2013 protocol to Japan-US tax treaty approved by US Senate",
//             "province": null,
//             "languageId": "37",
//             "containsYoutubeLink": false
//         }
//     ],
//     "resources": [],
//     "contacts": [],
//     "locale": null,
//     "authorised": false,
//     "userMessage": null
// }`;

function taxathand_response_modifier(responseCtrl, outputCtrl) {
    if (responseCtrl && outputCtrl && responseCtrl.split('_').length == 3 && outputCtrl.split('_').length == 3) {
        var result = [];
        var parsedJSON;
        var response = $('#' + responseCtrl).val();
        if (response) parsedJSON = JSON.parse(response);
        if (parsedJSON && parsedJSON.length) {
            $.each(parsedJSON, function (i, v) {
                result.push({
                    "uuid": v.uuid,
                    "title": v.title,
                    "teaserText": v.teaserText,
                    "relatedCountry": v.relatedCountry.displayName,
                    "relatedCountries": $.map(v.relatedCountries, function (cty) { return cty.displayName }).join(', '),
                    "publishDateTime": v.publishDateTime,
                    "sharingWebURL": v.sharingWebURL,
                    "imagePath": v.imagePath
                })
            });
            if (result.length) {
                $('#' + outputCtrl).val(JSON.stringify(result));
                textBoxChangeEvent(outputCtrl, $('#' + outputCtrl).attr('name'), $('#' + outputCtrl).val());
            }
        }
    }
}