var eventMethod = window.addEventListener ? 'addEventListener' : 'attachEvent';
var eventer = window[eventMethod];
var messageEvent = eventMethod == 'attachEvent' ? 'onmessage' : 'message';
eventer(messageEvent, function (e) {
    if (e.data == 'SaveAppForm') {
        var btnSaveToDB = document.getElementsByName('Save')[0];
        ButtonClicked(btnSaveToDB.id, btnSaveToDB.name, btnSaveToDB.value);
    } else if (e.data == 'SaveAsPdf') {
        var btnSaveAsPdf = document.getElementsByName('ExportToPDF')[0];
        ButtonClicked(btnSaveAsPdf.id, btnSaveAsPdf.name, btnSaveAsPdf.value);
    } else {
        var txtboxTax = document.getElementsByName('txtTY')[0];
        txtboxTax.value = e.data.TaxYear;
        textBoxChangeEvent(txtboxTax.id, txtboxTax.name, txtboxTax.value, '', '');
        var txtboxLE = document.getElementsByName('CurrentLE')[0];
        txtboxLE.value = e.data.LegalEntity;
        textBoxChangeEvent(txtboxLE.id, txtboxLE.name, txtboxLE.value, '', '');
        var varLocation = e.data.Location;
        var txtLocation = document.getElementsByName('txtLocation')[0];
        txtLocation.value = varLocation;
        textBoxChangeEvent(txtLocation.id, txtLocation.name, txtLocation.value, '', '');
        var varLocationID = e.data.LocationID;
        var txtLocationID = document.getElementsByName('txtLocationID')[0];
        txtLocationID.value = varLocationID;
        textBoxChangeEvent(txtLocationID.id, txtLocationID.name, txtLocationID.value, '', '');
        var varTaxYearID = e.data.TaxYearID;
        var txtTaxYearID = document.getElementsByName('txtTaxYearID')[0];
        txtTaxYearID.value = varTaxYearID;
        textBoxChangeEvent(txtTaxYearID.id, txtTaxYearID.name, txtTaxYearID.value, '', '');
        var varLegalEntityID = e.data.LegalEntityID;
        var txtLegalEntityID = document.getElementsByName('txtLegalEntityID')[0];
        txtLegalEntityID.value = varLegalEntityID;
        textBoxChangeEvent(txtLegalEntityID.id, txtLegalEntityID.name, txtLegalEntityID.value, '', '');
        var varPeriod = e.data.Period;
        var txtPeriod = document.getElementsByName('txtPeriod')[0];
        txtPeriod.value = varPeriod;
        textBoxChangeEvent(txtPeriod.id, txtPeriod.name, txtPeriod.value, '', '');
        var varType = e.data.Type;
        var txtType = document.getElementsByName('txtType')[0];
        txtType.value = varType;
        textBoxChangeEvent(txtType.id, txtType.name, txtType.value, '', '');
        var varHostUrl = e.data.HostUrl;
        var txtHostUrl = document.getElementsByName('txtHostUrl')[0];
        txtHostUrl.value = varHostUrl;
        textBoxChangeEvent(txtHostUrl.id, txtHostUrl.name, txtHostUrl.value, '', '');
        var varItemId = e.data.ItemId;
        var txtItemId = document.getElementsByName('txtItemId')[0];
        txtItemId.value = varItemId;
        textBoxChangeEvent(txtItemId.id, txtItemId.name, txtItemId.value, '', '');
        var varDisplayMode = e.data.Forms[0].DisplayMode;
        var txtDisplayMode = document.getElementsByName('txtDisplayMode')[0];
        txtDisplayMode.value = varDisplayMode;
        textBoxChangeEvent(txtDisplayMode.id, txtDisplayMode.name, txtDisplayMode.value, '', '');
        var varCurrentUser = e.data.CurrentUser.userCode;
        var txtCurrentUser = document.getElementsByName('txtCurrentUser')[0];
        txtCurrentUser.value = varCurrentUser;
        textBoxChangeEvent(txtCurrentUser.id, txtCurrentUser.name, txtCurrentUser.value, '', '');
        var varItemRoles = e.data.Forms[0].ItemRoles;
        var txtItemRolesbox = document.getElementsByName('txtItemRoles')[0];
        txtItemRolesbox.value = varItemRoles;
        textBoxChangeEvent(txtItemRolesbox.id, txtItemRolesbox.name, txtItemRolesbox.value, '', '');
        var varLoggedInUserRole = e.data.LoggedInUserRole;
        var txtLoggedInUserRole = document.getElementsByName('txtLoggedInUserRole')[0];
        txtLoggedInUserRole.value = varLoggedInUserRole;
        textBoxChangeEvent(txtLoggedInUserRole.id, txtLoggedInUserRole.name, txtLoggedInUserRole.value, '', '');
        var varFormRoles = e.data.Forms[0].FormRoles;
        var txtFormRoles = document.getElementsByName('txtFormRoles')[0];
        txtFormRoles.value = varFormRoles;
        textBoxChangeEvent(txtFormRoles.id, txtFormRoles.name, txtFormRoles.value, '', '');
        var varInstanceId = e.data.InstanceId;
        var txtInstanceId = document.getElementsByName('txtInstanceId')[0];
        txtInstanceId.value = varInstanceId;
        textBoxChangeEvent(txtInstanceId.id, txtInstanceId.name, txtInstanceId.value, '', '');
        var varParentDefinitionId = e.data.ParentDefinitionId;
        var txtParentDefinitionId = document.getElementsByName('txtParentDefinitionId')[0];
        txtParentDefinitionId.value = varParentDefinitionId;
        textBoxChangeEvent(txtParentDefinitionId.id, txtParentDefinitionId.name, txtParentDefinitionId.value, '', '');
        var varParentInstanceId = e.data.ParentInstanceId;
        var txtParentInstanceId = document.getElementsByName('txtParentInstanceId')[0];
        txtParentInstanceId.value = varParentInstanceId;
        textBoxChangeEvent(txtParentDefinitionId.id, txtParentDefinitionId.name, txtParentDefinitionId.value, '', '');
        var varSiteUrl = e.data.SiteUrl;
        var txtSiteUrl = document.getElementsByName('txtSiteUrl')[0];
        txtSiteUrl.value = varSiteUrl;
        textBoxChangeEvent(txtSiteUrl.id, txtSiteUrl.name, txtSiteUrl.value, '', '');
        var varListName = e.data.ListName;
        var txtListName = document.getElementsByName('txtListName')[0];
        txtListName.value = varListName;
        textBoxChangeEvent(txtListName.id, txtListName.name, txtListName.value, '', '');
        var specializedSecurityValue = e.data.SpecializedSecurity;
        var txtboxSpecializedSecurity = document.getElementsByName('txtSpecializedSecurity')[0];
        txtboxSpecializedSecurity.value = specializedSecurityValue;
        textBoxChangeEvent(txtboxSpecializedSecurity.id, txtboxSpecializedSecurity.name, txtboxSpecializedSecurity.value, '', '');
        var varTrackerId = e.data.TrackerId;
        var txtTrackerId = document.getElementsByName('txtTrackerId')[0];
        txtTrackerId.value = varTrackerId;
        textBoxChangeEvent(txtTrackerId.id, txtTrackerId.name, txtTrackerId.value, '', '');
        var vartxtModuleId = e.data.ModuleID;
        var txtModuleId = document.getElementsByName('txtModuleID')[0];
        txtModuleId.value = vartxtModuleId;
        textBoxChangeEvent(txtModuleId.id, txtModuleId.name, txtModuleId.value, '', '');
        var vartxtModule = e.data.Module;
        var txtModule = document.getElementsByName('txtModule')[0];
        txtModule.value = vartxtModule;
        textBoxChangeEvent(txtModule.id, txtModule.name, txtModule.value, '', '');
        var vartxtMasterObligation = e.data.MasterObligation;
        var txtMasterObligation = document.getElementsByName('txtMasterObligation')[0];
        txtMasterObligation.value = vartxtMasterObligation;
        textBoxChangeEvent(txtMasterObligation.id, txtMasterObligation.name, txtMasterObligation.value, '', '');
        var vartxtModuleCode = e.data.ModuleCode;
        var txtModuleCode = document.getElementsByName('txtModuleCode')[0];
        txtModuleCode.value = vartxtModuleCode;
        textBoxChangeEvent(txtModuleCode.id, txtModuleCode.name, txtModuleCode.value, '', '');
        var vartxtLocationCode = e.data.LocationCode;
        var txtLocationCode = document.getElementsByName('txtLocationCode')[0];
        txtLocationCode.value = vartxtLocationCode;
        textBoxChangeEvent(txtLocationCode.id, txtLocationCode.name, txtLocationCode.value, '', '');
        var vartxtSPSiteDocUrl = e.data.SPSiteDocUrl;
        var txtSPSiteDocUrl = document.getElementsByName('txtSPSiteDocUrl')[0];
        txtSPSiteDocUrl.value = vartxtSPSiteDocUrl;
        textBoxChangeEvent(txtSPSiteDocUrl.id, txtSPSiteDocUrl.name, txtSPSiteDocUrl.value, '', '');
    }
}, false);